### ISSUE TITLE
README.md File styling

### ISSUE THREAD

**Issue by chintanjosh** [MedicalAppInfibeam/DoctorsWebApp#3]
Keep the styling of README.md file proper.
You can look into [this](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) for help.

**Comment by shrut1996** [comment]
@chintanjosh I have made a primitive template for now and as time goes, I'll update it as per advancement of the Project.

**Comment by chintanjosh** [comment]
Okay @shrut1996  Great keep it up

**Comment by shrut1996** [comment]
@chintanjosh  Done :+1:
