### ISSUE TITLE
Usage of .gitignore

### ISSUE THREAD

**Issue by chintanjosh** [MedicalAppInfibeam/DoctorsWebApp#98]
Hello Team,
Some files are of no use to others like .pyc files, some files are to be kept private like environment files, some files can differ as per the user.

So to avoid those kind of files we use .gitignore.
You can see the usage instructions [here](https://help.github.com/articles/ignoring-files/).

Identify such files and keep them in gitignore.

**Comment by shrut1996** [comment]
@chintanjosh  Sir, I did this [https://github.com/MedicalAppInfibeam/DoctorsWebApp/commit/64d70d741e72acafa66ee354080bc59110d60b6c](here) but the problem we faced was while migrating to the database in a local server as there are some files like the `0001.pyc` files that are required.

So what we are doing currently is that @harry14 is the only one hosting the server and maintaining the database and pushes the .pyc files while the changes others push are only the .py, .css, .js, .html etc. files.

**Comment by chintanjosh** [comment]
@shrut1996 .pyc files should not create any issues in migrating, don't know what is causing it. Don't worry for this as of now, you can look into this when the whole app is done.

**Comment by garvit-gupta** [comment]
Fixed by #160

**Comment by chintanjosh** [comment]
Great work. Keep it up.
